# comentarios
#CI de Nivel 02 - Execução agendada
#nome da pipeline
name: 'Execução Agendada'

#pela identação identifica oq vai estar dentro
on:
  schedule:
    #cronograma de execução
    #cada numero do cron significa alguma coisa
    #1- minuto, 2- hora, 3-dia do mês, 4- mês, 5-dia da semana
    #roda toda sexta-feira a meia noite
    - cron: '0 0 * * 5'

  #quando acontecer um push tem que rodar a pipe automaticamente
  push:
    branches:
      - master

#Jobs = tarefas dentro da pipeline
jobs:
  #nome do job
  e2e-tests:
    #maquina onde o job vai rodar
    runs-on: ubuntu-latest

    #passos do job
    steps:
      #clone do projeto - essas actions já existem só precisamos usar.
      - uses: actions/checkout@v4

      #action para fazer a instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      #istalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      #instalação das dependencias
      - name: Istalando dependências
        run: yarn

      #instalação dos browser do Playwright
      - name: Instalando Browsers do Playwright
        run: yarn playwright install

      #executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e

      # salvar o relatório do Playwright
      - name: Salvar relatório Playwright
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-actiontest
          path: playwright-report/
